CREATE TABLE sellers(id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL, supplier TEXT, fruits TEXT []);

CREATE TABLE fruit(id BIGSERIAL PRIMARY KEY, name TEXT UNIQUE NOT NULL, price NUMERIC CHECK (price>=0));

CREATE TABLE suppliers(id BIGSERIAL PRIMARY KEY, company TEXT UNIQUE NOT NULL);
